//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpoint) DeepCopyInto(out *ContainerCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpoint.
func (in *ContainerCheckpoint) DeepCopy() *ContainerCheckpoint {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointClass) DeepCopyInto(out *ContainerCheckpointClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointClass.
func (in *ContainerCheckpointClass) DeepCopy() *ContainerCheckpointClass {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpointClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointClassList) DeepCopyInto(out *ContainerCheckpointClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerCheckpointClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointClassList.
func (in *ContainerCheckpointClassList) DeepCopy() *ContainerCheckpointClassList {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpointClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointClassSpec) DeepCopyInto(out *ContainerCheckpointClassSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointClassSpec.
func (in *ContainerCheckpointClassSpec) DeepCopy() *ContainerCheckpointClassSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointClassStatus) DeepCopyInto(out *ContainerCheckpointClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointClassStatus.
func (in *ContainerCheckpointClassStatus) DeepCopy() *ContainerCheckpointClassStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointContent) DeepCopyInto(out *ContainerCheckpointContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointContent.
func (in *ContainerCheckpointContent) DeepCopy() *ContainerCheckpointContent {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpointContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointContentList) DeepCopyInto(out *ContainerCheckpointContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerCheckpointContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointContentList.
func (in *ContainerCheckpointContentList) DeepCopy() *ContainerCheckpointContentList {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpointContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointContentSpec) DeepCopyInto(out *ContainerCheckpointContentSpec) {
	*out = *in
	out.ContainerCheckpointRef = in.ContainerCheckpointRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointContentSpec.
func (in *ContainerCheckpointContentSpec) DeepCopy() *ContainerCheckpointContentSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointContentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointContentStatus) DeepCopyInto(out *ContainerCheckpointContentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointContentStatus.
func (in *ContainerCheckpointContentStatus) DeepCopy() *ContainerCheckpointContentStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointContentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointList) DeepCopyInto(out *ContainerCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointList.
func (in *ContainerCheckpointList) DeepCopy() *ContainerCheckpointList {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointRef) DeepCopyInto(out *ContainerCheckpointRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointRef.
func (in *ContainerCheckpointRef) DeepCopy() *ContainerCheckpointRef {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointSpec) DeepCopyInto(out *ContainerCheckpointSpec) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointSpec.
func (in *ContainerCheckpointSpec) DeepCopy() *ContainerCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpointStatus) DeepCopyInto(out *ContainerCheckpointStatus) {
	*out = *in
	if in.CheckpointTime != nil {
		in, out := &in.CheckpointTime, &out.CheckpointTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpointStatus.
func (in *ContainerCheckpointStatus) DeepCopy() *ContainerCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}
