---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpointcontents
  - containercheckpoints
  - podcheckpointcontents
  - podcheckpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpointcontents/status
  - containercheckpoints/status
  - podcheckpointcontents/status
  - podcheckpoints/status
  verbs:
  - get
  - patch
  - update
