---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpointclasses
  - podcheckpointclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpointcontents
  - containercheckpoints
  - podcheckpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpointcontents/status
  - containercheckpoints/status
  - podcheckpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - containercheckpoints/finalizers
  verbs:
  - update
- apiGroups:
  - checkpointing.zacchaeuschok.github.io
  resources:
  - podcheckpointcontents
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
