apiVersion: checkpointing.zacchaeuschok.github.io/v1
kind: ContainerCheckpoint
metadata:
  name: nginx-container-checkpoint
  namespace: default
spec:
  source:
    podName: nginx-sample
    containerName: nginx
  deletionPolicy: Retain
