apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  containers:
    - name: nginx
      image: busybox
      imagePullPolicy: Never
      command: ["/bin/sh", "-c"]
      args:
        - |
          i=0
          while true; do
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') nginx:$i"
            i=$((i+1))
            sleep 10
          done
    - name: sidekick
      image: busybox
      imagePullPolicy: Never
      command: ["/bin/sh", "-c"]
      args:
        - |
          j=0
          while true; do
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') sidekick:$j"
            j=$((j+1))
            sleep 10
          done
