apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  containers:
    - name: nginx
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          i=0
          while true; do
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') nginx:$i" >> /mnt/checkpoints/nginx.log
            i=$((i+1))
            sleep 10
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /mnt/checkpoints

    - name: sidekick
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          j=0
          while true; do
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') sidekick:$j" >> /mnt/checkpoints/sidekick.log
            j=$((j+1))
            sleep 10
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /mnt/checkpoints

  volumes:
    - name: shared-logs
      emptyDir: {}
