apiVersion: v1
kind: Pod
metadata:
  name: stateful-app
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: node1  # Ensure it runs on node1
  containers:
  - name: counter
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      counter=0
      while true; do
        echo "Counter: $counter"
        counter=$((counter+1))
        sleep 10
      done
