apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-checkpoint-sidecar
rules:
  # --------------------------------------------------------------------
  # CRDs the side‑car watches / updates
  # --------------------------------------------------------------------
  - apiGroups:
      - checkpointing.zacchaeuschok.github.io
    resources:
      - containercheckpoints
      - containercheckpoints/status
      - containercheckpointcontents
      - containercheckpointcontents/status
      - podcheckpoints
      - podcheckpoints/status
      - podcheckpointcontents
      - podcheckpointcontents/status
    verbs: [get, list, watch, create, update, patch]

  # --------------------------------------------------------------------
  # Pods – we must patch the annotation once the restore is done
  # --------------------------------------------------------------------
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [get, list, watch, update, patch]

  # --------------------------------------------------------------------
  # Pods/exec - needed for checkpoint transfer between nodes
  # --------------------------------------------------------------------
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: [create, get]

  # --------------------------------------------------------------------
  # (Optional) node proxy/metrics rules – only needed if you
  # go through the Kubernetes API to reach the kubelet.  The current
  # code talks to the kubelet directly over 10250, so these can stay
  # or be removed without harm.
  # --------------------------------------------------------------------
  - apiGroups: [""]
    resources: ["nodes/proxy", "nodes/stats", "nodes/log", "nodes/metrics"]
    verbs: [create, get, post, update, list, watch]

  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: container-checkpoint-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: container-checkpoint-sidecar
subjects:
  - kind: ServiceAccount
    name: container-checkpoint-sidecar
    namespace: external-checkpointer-system
